-- Liste des colocations avec leur gestionnaire (testé ok)

Select ID_COLOCATION ,NOM_COLOCATION AS COLOCATION,NOM_PERSONNE AS GESTIONNAIRE
from COLOCATION,PERSONNE
where COLOCATION.ID_PERSONNE=PERSONNE.ID_PERSONNE;


