-- Ensemble des membres d'un colocation donnée

Select ID_PERSONNE, NOM_PERSONNE AS MEMBRE
from COLOCATION, CONTRAT_MEMBRE, PERSONNE
where (NOM_COLOCATION= 'XX' or COLOCATION.ID_COLOCATION=XX)
      and COLOCATION.ID_COLOCATION=CONTRAT_MEMBRE.ID_COLOCATION
      and CONTRAT_MEMBRE.ID_PERSONNE=PERSONNE.ID_PERSONNE;
